### ISSUE TITLE
Changes to presentation components

### ISSUE THREAD

**Issue by bendq** [Microsoft/MCW-Windows-Server-and-SQL-Server-2008-R2-End-of-Support-Planning#2]
•	Remove Velostrata as acquired by Google
•	I thought TSO Logic was a partner now, it is missing
•	Refactor is inaccurate – it doesn’t have to be first party PaaS to do this. It can in fact be utilizing Infra as code and this is a far more commons scenario – i.e. Terraform with ansible or chef tied into the CI/CD pipeline and releases. 
•	Re-architect and refactor are confusing IMO. I personally believe using App Service, Infra as Code or Containers fits these descriptions. Modernising traditional apps can be done with containers (.net or Java) or Infra as code. Also we are talking about AKS only – no inclusion for openshift, DC/OS, Docker EE or other third party container management solution?
•	Rebuild is talking about first party azure PaaS only.  A lot of customers will look at cloud foundry as an alternate solution
•	Optimize – BCDR talks about VM and SQL backup only. What happens in the instance that they customer utilizes a container based solution or cloud foundry? Also Backup is mentioned here only – where is the DR portion? Whether through ASR, resilient build of architecture or 3rd party
•	Slide 30 misspelling of “eligible”

**Comment by DawnmarieDesJardins** [comment]
Per jstulo, all feedback address and incorporated as possible.  Closing this issue.
