### ISSUE TITLE
WDS - trainer presentation (PPT)

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Windows-Server-and-SQL-Server-2008-R2-End-of-Support-Planning#3]
Hello.  I made several formatting changes to the PPT, renamed it to follow current naming conventions, and uploaded the new file to GitHub.  Please make sure to use my PPT deck to update what's below so we don't lose my updates.

Slide 9 - images need to be flat (not several boxes) and alt-text needs to explain it in one box.  There's alt-text for the cloud and the building, but not what it's supposed to mean. I've flattened the image, please fill in the alt-text and describe what it's depicting. 
Slide 10 - missing alt-text
Slide 11 - missing alt-text
Slide 19 - missing alt-text
Slide 21 - missing alt-text - Notes say: Update to use Extended Security Updates & Add TCO calc (I think that's from our last meeting)
Slide 22 - 29 Images need to be flat & add alt-text
Slide 30 - presenter notes say remove premium assurance??
Slide 34 - presenter notes say Region/country...not sure what that means.  I changed your objection to countries or regions per CELA, was that a meeting note?
Slide 35 - I added this one.  You asked 6 customer objections but only answered 5.  Need to fill in answer for this one too.

**Comment by paulopsgility** [comment]
By  "images need to be flat" are you asking for them to be grouped or pasted in as images?

**Comment by DawnmarieDesJardins** [comment]
They have to be one image. Easy to use snip it to do it.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by paulopsgility** [comment]
Slide deck is updated. all the alt-text was added, images flattened, answered the customer objection. Deleted my personal notes from the slides (yes they were from one of the meetings)
